# This is a basic workflow to help you get started with Actions

name: Deploy external publish triggers

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Run SIGGRAPH publish project
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: sjaakjules
          repo: more-than-human-knowledge-management
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: publish.yml
          trigger_workflow: true
          wait_workflow: false
      - name: Deploy Web 
        run: |
          echo "Deploy Web"
          sleep 10s
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #    - uses: actions/checkout@v2

      # Runs a single command using the runners shell
   #   - name: Run a one-line script
  #      run: echo Hello, world!

      # Runs a set of commands using the runners shell
  #    - name: Run a multi-line script
  #      run: |
  #        echo Add other actions to build,
   #       echo test, and deploy your project.
